### ISSUE TITLE
Inserting Youtube video URL as variable from clipboard puts unneccessary spaces in it

### ISSUE THREAD

**Issue by tonyrulez** [knqyf263/pet#136] opened 2020-05-14 06:22 UTC
I made the following snippet for Youtube-DL:

```
[[snippets]]
  description = "Download Youtube video"
  command = "youtube-dl -o '/home/tonyrulez/Youtube/%(upload_date)s - %(uploader)s - %(title)s.%(ext)s' <url>"
  output = ""
```
When I run this snippet and it asks for the url, I copy it from the browser, but it gets spaced out.
What I copied: `https://www.youtube.com/watch?v=dQw4w9WgXcQ`
How it gets pasted: `https://www.youtube . c om / w a t c h ? v = d Q w 4 w 9 W g X c Q`
In result, youtube-dl does not recognise the url, more precisely it only recognises the first half, until the first space:
```
[generic] www: Requesting header
WARNING: Could not send HEAD request to https://www.youtube: <urlopen error [Errno -2] Name or service not known>
[generic] www: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
exit status 1
```
Why is it stretching out the URL?

**Comment by spaddex** [comment] 2020-06-02 16:12
Feels like this might be a dupe of #132?

**Comment by tonyrulez** [comment] 2020-06-02 16:13
Yep, this might be the reason why the first couple characters don't get spaced out.

**Closed** 2024-02-19 17:01 UTC
